export const RULES_TEXT = [
  "中文：",
  "例休登記規則",
  "1. 請依照表格上公告的日期範圍輸入。",
  "2. 第一次登記請輸入工號和日期，例如：BA179 6/3。若表格日期很清楚，也可輸入：BA179 3。",
  "3. 第一次完成後，之後可以只輸入日期，例如：6/4 或 4。",
  "4. 每個日期每組最多 2 人，額滿請改選其他日期。",
  "5. 已登記後如需變更，請聯絡組長。",
  "6. 查詢日期狀況請輸入：查詢 6/3 或 查詢 3。",
  "",
  "English:",
  "Holiday registration rules",
  "1. Please enter a date within the date range shown in the sheet.",
  "2. For the first registration, enter your worker ID and date, for example: BA179 6/3. If the sheet date is clear, you may also enter: BA179 3.",
  "3. After the first registration, you can enter only the date, for example: 6/4 or 4.",
  "4. Each team can register up to 2 people per date. If full, please choose another date.",
  "5. If you need to change a registered date, please contact the leader.",
  "6. To check a date, enter: status 6/3 or status 3.",
  "",
  "Tiếng Việt:",
  "Quy định đăng ký ngày nghỉ",
  "1. Vui lòng nhập ngày nằm trong phạm vi ngày được thông báo trên bảng.",
  "2. Lần đầu đăng ký, vui lòng nhập mã nhân viên và ngày, ví dụ: BA179 6/3. Nếu ngày trên bảng rõ ràng, cũng có thể nhập: BA179 3.",
  "3. Sau lần đăng ký đầu tiên, lần sau chỉ cần nhập ngày, ví dụ: 6/4 hoặc 4.",
  "4. Mỗi nhóm tối đa 2 người cho mỗi ngày. Nếu đã đủ, vui lòng chọn ngày khác.",
  "5. Nếu cần đổi ngày đã đăng ký, vui lòng liên hệ tổ trưởng.",
  "6. Để kiểm tra một ngày, nhập: kiem tra 6/3 hoặc kiem tra 3.",
].join("\n");
