export const RULES_TEXT = [
  "中文：",
  "例休登記規則",
  "1. 第一次登記請輸入工號和日期，例如：BA179 6/3。",
  "2. 第一次完成後，之後可以只輸入日期，例如：6/4。",
  "3. 每個日期每組最多 2 人，額滿請改選其他日期。",
  "4. 已登記後如需變更，請聯絡組長。",
  "5. 查詢日期狀況請輸入：查詢 6/3。",
  "",
  "English:",
  "Holiday registration rules",
  "1. For the first registration, enter your worker ID and date, for example: BA179 6/3.",
  "2. After the first registration, you can enter only the date, for example: 6/4.",
  "3. Each team can register up to 2 people per date. If full, please choose another date.",
  "4. If you need to change a registered date, please contact the leader.",
  "5. To check a date, enter: status 6/3.",
  "",
  "Tiếng Việt:",
  "Quy định đăng ký ngày nghỉ",
  "1. Lần đầu đăng ký, vui lòng nhập mã nhân viên và ngày, ví dụ: BA179 6/3.",
  "2. Sau lần đăng ký đầu tiên, lần sau chỉ cần nhập ngày, ví dụ: 6/4.",
  "3. Mỗi nhóm tối đa 2 người cho mỗi ngày. Nếu đã đủ, vui lòng chọn ngày khác.",
  "4. Nếu cần đổi ngày đã đăng ký, vui lòng liên hệ tổ trưởng.",
  "5. Để kiểm tra một ngày, nhập: kiem tra 6/3.",
].join("\n");
